#pragma once
#ifndef INVENTORY_H
#define INVENTORY_H

#include <map>
#include <string>
using namespace std;

class Inventory {
public:
    /*
    * Default Constructor generated by compiler will suffice.
    * There is no need to create a custom constructor because there are no variables that need to be set immediately.
    */
    // Function reads input file and populates frequencyMap
    void readInputFile(const string& fileName);

    // Function finds frequency of a specific item - Menu Option 1
    void findItemFrequency();

    // Function prints all items with amounts - Menu Option 2
    void printAllItemFrequencies();

    // Function prints histogram of item amounts - Menu Option 3
    void printAllItemHistogram();

    // Save frequency data to frequency.dat
    void saveData();

private:
    //initialize a Map to store item and item frequency
    map<string, int> frequencyMap;
    const int COLUMN_SIZE = 12;
};
#endif